/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pck_View;

import java.awt.event.ActionEvent;

/**
 *
 * @author Mateus
 */
public class IndexView extends javax.swing.JFrame {

    /**
     * Creates new form indexView
     */
    public IndexView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelSubTitulo2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelIconPedidos2 = new javax.swing.JLabel();
        jLabelDescPedids2 = new javax.swing.JLabel();
        jLabelIconItens2 = new javax.swing.JLabel();
        jLabelDescItens2 = new javax.swing.JLabel();
        jLabelIconProdutos2 = new javax.swing.JLabel();
        jLabelDescProdutos2 = new javax.swing.JLabel();
        jLabelIconClientes2 = new javax.swing.JLabel();
        jLabelDescClientes2 = new javax.swing.JLabel();
        jButtonSair2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 0));
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitulo2.setBackground(new java.awt.Color(173, 212, 156));
        jLabelTitulo2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(64, 83, 62));
        jLabelTitulo2.setText(" -- Sistema Pedido");
        jLabelTitulo2.setToolTipText("");
        jLabelTitulo2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabelTitulo2.setOpaque(true);

        jLabelSubTitulo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelSubTitulo2.setForeground(new java.awt.Color(64, 83, 62));
        jLabelSubTitulo2.setText("Gerenciamento de cadastros");

        jSeparator4.setBackground(new java.awt.Color(53, 149, 9));
        jSeparator4.setForeground(new java.awt.Color(53, 149, 9));

        jLabelIconPedidos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconPedidos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pck_Img/IconPedido.png"))); // NOI18N
        jLabelIconPedidos2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 149, 9), 1, true));
        jLabelIconPedidos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIconPedidos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconPedidosMouseClicked(evt);
            }
        });

        jLabelDescPedids2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescPedids2.setForeground(new java.awt.Color(53, 149, 9));
        jLabelDescPedids2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescPedids2.setText("Pedidos");

        jLabelIconItens2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconItens2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pck_Img/IconItem.png"))); // NOI18N
        jLabelIconItens2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 149, 9), 1, true));
        jLabelIconItens2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIconItens2.setMaximumSize(new java.awt.Dimension(152, 152));
        jLabelIconItens2.setMinimumSize(new java.awt.Dimension(152, 152));
        jLabelIconItens2.setPreferredSize(new java.awt.Dimension(152, 152));
        jLabelIconItens2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconItensMouseClicked(evt);
            }
        });

        jLabelDescItens2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescItens2.setForeground(new java.awt.Color(53, 149, 9));
        jLabelDescItens2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescItens2.setText("Itens");

        jLabelIconProdutos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconProdutos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pck_Img/IconProduto.png"))); // NOI18N
        jLabelIconProdutos2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 149, 9), 1, true));
        jLabelIconProdutos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIconProdutos2.setMaximumSize(new java.awt.Dimension(152, 152));
        jLabelIconProdutos2.setMinimumSize(new java.awt.Dimension(152, 152));
        jLabelIconProdutos2.setPreferredSize(new java.awt.Dimension(152, 152));
        jLabelIconProdutos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconProdutosMouseClicked(evt);
            }
        });

        jLabelDescProdutos2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescProdutos2.setForeground(new java.awt.Color(53, 149, 9));
        jLabelDescProdutos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescProdutos2.setText("Produtos");

        jLabelIconClientes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconClientes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pck_Img/IconClientes.png"))); // NOI18N
        jLabelIconClientes2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 149, 9), 1, true));
        jLabelIconClientes2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIconClientes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconClientesMouseClicked(evt);
            }
        });

        jLabelDescClientes2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescClientes2.setForeground(new java.awt.Color(53, 149, 9));
        jLabelDescClientes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescClientes2.setText("Clientes");

        jButtonSair2.setBackground(new java.awt.Color(173, 212, 156));
        jButtonSair2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSair2.setForeground(new java.awt.Color(64, 83, 62));
        jButtonSair2.setText("SAIR");
        jButtonSair2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jButtonSair2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair2.setFocusable(false);
        jButtonSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSubTitulo2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelDescPedids2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIconPedidos2))
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconItens2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescItens2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconProdutos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescProdutos2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconClientes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescClientes2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(513, 513, 513))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabelSubTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIconClientes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelIconPedidos2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelIconItens2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDescPedids2)
                            .addComponent(jLabelDescItens2)
                            .addComponent(jLabelDescClientes2)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelIconProdutos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDescProdutos2)))
                .addGap(72, 72, 72)
                .addComponent(jButtonSair2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0); // Encerra o programa
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jLabelIconClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconClientesMouseClicked
        ClientesView segundaTela = new ClientesView(); // Substitua "SegundaTela" pelo nome da sua classe da segunda tela
        segundaTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelIconClientesMouseClicked

    private void jLabelIconProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconProdutosMouseClicked
        ProdutosView segundaTela = new ProdutosView(); // Substitua "SegundaTela" pelo nome da sua classe da segunda tela
        segundaTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelIconProdutosMouseClicked

    private void jLabelIconItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconItensMouseClicked
        Itens_pedidoView segundaTela = new Itens_pedidoView(); // Substitua "SegundaTela" pelo nome da sua classe da segunda tela
        segundaTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelIconItensMouseClicked

    private void jLabelIconPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconPedidosMouseClicked
        PedidosView segundaTela = new PedidosView(); // Substitua "SegundaTela" pelo nome da sua classe da segunda tela
        segundaTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelIconPedidosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair2;
    private javax.swing.JLabel jLabelDescClientes2;
    private javax.swing.JLabel jLabelDescItens2;
    private javax.swing.JLabel jLabelDescPedids2;
    private javax.swing.JLabel jLabelDescProdutos2;
    private javax.swing.JLabel jLabelIconClientes2;
    private javax.swing.JLabel jLabelIconItens2;
    private javax.swing.JLabel jLabelIconPedidos2;
    private javax.swing.JLabel jLabelIconProdutos2;
    private javax.swing.JLabel jLabelSubTitulo2;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
